### ISSUE TITLE
Bat not showing full text file

### ISSUE THREAD

**Issue by domglusk** [Freed-Wu/fzf-tab-source#12]
![1-0105-Jan172024](https://github.com/Freed-Wu/fzf-tab-source/assets/64805993/bb7d6e8f-353c-447c-b01b-8b4ba99e2652)
Image shows bat output on bottom pane for the same file being previewed and truncated in the top pane.
I'm using your ~/.lessfilter and kitty. Here are some environmental variables and options I think may be relevant
```zsh
LS_OPTIONS=-N --color=tty -T 0
LESS=-r -M -r -M --mouse -S -I
LESSOPEN=|/usr/bin/lesspipe.sh %s
LESSQUIET=1
PAGER=less
FZF_DEFAULT_OPTS=--cycle --layout=reverse --height=90% --preview-window=wrap --scroll-off=3 --bind tab:down,shift-tab:up

bat config =
--color='always'
--theme='Coldark-Dark'
--style=plain
--pager=less
--wrap=character
```
Running openSUSE Tumbleweed with lesspipe installed from source and using zcomet with these plugins
```zsh
Plugins:
  3v1n0/zsh-bash-completions-fallback
  aubreypwd/zsh-plugin-require
  Freed-Wu/fzf-tab-source
  Freed-Wu/zsh-colorize-functions
  Freed-Wu/zsh-completions-for-cross-compilers
  Freed-Wu/zsh-help
  jdujava/fzf-tab-jd
  Licheam/zsh-ask
  mdumitru/last-working-dir
  microsoft/inshellisense
  zdharma-continuum/fast-syntax-highlighting
  zpm-zsh/colorize
  zpm-zsh/ssh
  zsh-users/zsh-autosuggestions
FPATH elements:
  corvofeng/joe-completion
  grigorii-zander/zsh-npm-scripts-autocomplete
  MenkeTechnologies/zsh-more-completions
  nix-community/nix-zsh-completions
  sainnhe/zsh-completions
  sambergo/zsh-prettier-completion
  syohex/zsh-misc-completions
```

**Comment by Freed-Wu** [comment]
Very weird, I haven't met this situation. My `~/.config/bat/config` is [here](https://github.com/Freed-Wu/Freed-Wu/blob/main/.config/bat/config). My `$FZF_DEFAULT_OPTS` is [here](https://github.com/Freed-Wu/Freed-Wu/blob/main/.bash_profile#L94). Can them help you?

**Comment by domglusk** [comment]
Doesn't seem to help, but I figured when commenting out my env variables that unsetting FZF_TMUX_HEIGHT=$((LINES - 20)) makes tab just print a new line, not doing anything

**Comment by Freed-Wu** [comment]
Can you try `FZF_TMUX_HEIGHT=100%`?

**Comment by Freed-Wu** [comment]
> Bat not showing full text file

IMO, `FZF_TMUX_HEIGHT=$((LINES - 20))` set `FZF_TMUX_HEIGHT=4`, so it only display 4 lines. set `FZF_TMUX_HEIGHT=100%` should can get full height of your terminal.

> unsetting FZF_TMUX_HEIGHT=$((LINES - 20)) makes tab just print a new line

By default, fzf-tab will set `${FZF_TMUX_HEIGHT:=$(( min(max(lines, 100), LINES / 3 * 2)  ))}`. <https://github.com/Aloxaf/fzf-tab/blob/c2b4aa5ad2532cca91f23908ac7f00efb7ff09c9/lib/-ftb-fzf#L92>.
However, [zsh-colorize-functions](https://github.com/Freed-Wu/zsh-colorize-functions) has a bug break `min` and `max`, so it just print an empty result, that is a new line. I've fixed this bug in latest version.

**Comment by domglusk** [comment]
I'm still getting the issue, even after disabling zsh-colorize-functions

**Comment by domglusk** [comment]
I was able to fix it by using
```zsh
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --pager=always ${(Q)realpath}'
```

**Comment by Freed-Wu** [comment]
1. What is your plugin version? Is it latest?
2. What is the result of `FZF_TMUX_HEIGHT=100%`?

**Comment by domglusk** [comment]
Sorry for the late reply. Setting ```FZF_TMUX_HEIGHT=100%``` doesn't change anything with the preview

**Comment by domglusk** [comment]
I don't know if it's relevant or not but [fifc](https://github.com/gazorby/fifc) for fish is working with previews
![1-0346-Jan242024](https://github.com/Freed-Wu/fzf-tab-source/assets/64805993/d53b9742-faca-4b6b-a735-afd48e76135e)

**Comment by domglusk** [comment]
Related to previews, how do I make directory completions do ls/eza without -l, I've tried changing it in your~/.lessfilter but it isn't changing anything. I'd rather have it just do eza --oneline rather than eza -l

**Comment by Freed-Wu** [comment]
> FZF_TMUX_HEIGHT

If you don't use tmux, `FZF_TMUX_HEIGHT=X` should not be used. If you use tmux, perhaps your fzf version is not latest to support `FZF_TMUX_HEIGHT=X%`. just `FZF_TMUX_HEIGHT=X` and `X` is your `$HEIGHT`.

> if it's relevant

Not related, it is a fish plugin.

> but it isn't changing anything.

`eza --oneline` in `~/.lessfilter` works for me.

**Comment by domglusk** [comment]
Is it possible that less pipe isn't respecting my ~/.lessfilter?

**Comment by Freed-Wu** [comment]
1. What is your plugin version? Is it latest?
2. Do you use tmux?
3. You said:

```sh
zstyle ':fzf-tab:complete:*:*' fzf-preview 'bat --color=always --pager=always ${(Q)realpath}'
```

Can work.

Can

```sh
zstyle ':fzf-tab:complete:*:*' fzf-preview 'less $realpath'
```

work?

4. What is the result?

```sh
(($+commands[less])) && [ -x ~/.lessfilter ]
```

**Comment by Freed-Wu** [comment]
I doubt you forget `chmod +x ~/.lessfilter`? lesspipe require it is an executable file.

**Comment by domglusk** [comment]
I never realized it had to be an executable, after making it an executable everything works just fine, thank you for helping me.
